#!/bin/bash
SGE_ROOT=/opt/sge; export SGE_ROOT
SGE_CELL=default; export SGE_CELL
SGE_CLUSTER_NAME=ec3; export SGE_CLUSTER_NAME
SGE_QMASTER_PORT=6444; export SGE_QMASTER_PORT
SGE_EXECD_PORT=6445; export SGE_EXECD_PORT
